version: 1

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true


build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

sphinx:
   configuration: docs/source/conf.py

formats: all
